# Generated by Django 4.1.5 on 2023-01-03 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksAdmin',
            fields=[
                ('tasks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.tasks')),
            ],
            bases=('website.tasks',),
        ),
    ]
